### ISSUE TITLE
Unexpected failure message for failing `HttpResponse::shouldHaveHeader` assertion

### ISSUE THREAD

**Issue by mervyn-mccreight** [kotest/kotest-assertions-ktor#27]
## Expected behavior
When an assertion fails I expect the failure message to be like 
`Response should have header <header-name>=<expected-header-value> but was <header-name>=<actual-header-value>`.

## Current behavior
The failure message is like 
`Response should have header <header-name>=<HttpResponse::toString> but <header-name>=<actual-header-value>`.

## Metadata
library-version: 2.0.0
ktor-version: 2.3.10
kotest-version: 5.8.1

**Comment by mervyn-mccreight** [comment]
If the expected behavior makes sense to you, I'd be happy to provide a fix :)

**Comment by Kantis** [comment]
Fixed by #24 I believe
